---
title: "CusRel-Leaflet"
output: html_document
---
```{r}
install.packages("cowplot")
```

```{r}
library(leaflet)
library(tidyverse)
library(sf)
library(RColorBrewer)
library(randomcoloR)
library(geojsonio)
```

```{r}
# Read in data
cus_rel_data <- read_csv("Clean-CusRel-data.csv")
```

```{r}
# Add Resolve Time, Incident + Receive Date; Create Label for Popup
cus_rel_data <- cus_rel_data %>% 
  mutate(ResolveTime = round(as.numeric(difftime(as.POSIXct(ResolvedDateTime), as.POSIXct(ReceivedDateTime), units = "days"))), 
         ReceivedDate = as.Date(ReceivedDateTime, "%m/%d/%y", tz="PST8PDT"), 
         IncidentDate = as.Date(IncidentDateTime, "%m/%d/%y", tz="PST8PDT")) %>% 
  mutate(Label = str_c("<b>Received Date:</b> ", ReceivedDate, "<br/>",
                       "<b>Incident Date:</b> ", IncidentDate, "<br/>",
                       "<b>Location:</b> ", Location, "<br/>", 
                       "<b>Destination:</b> ", Destination , "<br/>",
                       "<b>Route:</b> ", Route, " &nbsp;&nbsp ", "<b>Vehicle #:</b> ", VehNo, "<br/>", 
                       "<b>Resolve Time:</b> ", ResolveTime, " day(s)<br/>", 
                       "<b>Reason(s):</b> ", Reason1, "&nbsp", Reason2,
                       "<b>Ticket Number:</b> ", FileNum, "<br/>" 
                       )) # Add a Label for Popup
```

```{r}
# Palette
contact_sources <- unique(cus_rel_data$ContactSource) # get unique contact sources
contact_source_palette <- colorFactor(palette="RdBu", domain=contact_sources)
color_list <- contact_source_palette(contact_sources)

n <- 115
website_route_palette <- distinctColorPalette(n)
```

```{r}
#Stops Data (from static file)
website_stops <- geojson_read("UniqueStops_Spring21_MS.json", what = "sp")
website_stops_sf <- st_as_sf(website_stops)
```

```{r}
#Routes Data (from API)
extract_NB_waypoint_columns <- function(patterns, colnames){
  my_waypoints <- as_tibble(patterns) %>%
    pull(Waypoints)
  my_waypoints <- my_waypoints[[1]] %>%
    dplyr::select(one_of(colnames))
  return(my_waypoints)
}

route_data <- "http://api.actransit.org/transit/route/ALL/waypoints/" %>% 
  GET(query = list(token = "BC36B05ADC9CB9A7977DD5A8878937DA")) %>% 
  content(as = "text") %>% 
  fromJSON() %>% 
  as_tibble()

route_data %>%
  mutate(Waypoints=purrr::map(Patterns, extract_NB_waypoint_columns, c("Longitude", "Latitude")))

all_patterns <- route_data %>%
  pull(Patterns)

waypoint_longitude <- map(all_patterns, extract_NB_waypoint_columns, "Longitude")

route_data <- route_data %>% 
  select(RouteAlpha, Patterns) %>% 
  dplyr::mutate(Longitude = pmap(list(Patterns), extract_NB_waypoint_columns, "Longitude"),
                Latitude = pmap(list(Patterns), extract_NB_waypoint_columns, "Latitude"))

#Convert route_data to SF 
route_data <- route_data %>% unnest(c(Longitude, Latitude)) 
route_data <- st_as_sf(route_data, coords = c("Longitude", "Latitude"), crs = 4326)

#Convert route_data from point to multilinestring
route_data <- route_data %>% 
  group_by(RouteAlpha) %>% 
  summarise(do_union = FALSE) %>% 
  st_cast("MULTILINESTRING")

#List of route numbers 
routeNums <- cus_rel_data$Route %>% 
  sort() %>% 
  unique()
```

```{r}
the_map <- cus_rel_data %>%
  leaflet() %>%
    addProviderTiles(providers$Stamen.TonerLite) %>%
    addCircleMarkers(lat = ~Latitude, lng = ~Longitude, 
                     fill = TRUE, fillColor = ~contact_source_palette(ContactSource), 
                     fillOpacity = 0.6, stroke = FALSE, 
                     color = ~contact_source_palette(ContactSource), 
                     popup = ~Label) %>%
   addLegend("bottomright", colors = color_list, labels = contact_sources, title = "Contact Source") %>% 
   addPolylines(data = route_data, label = route_data$RouteAlpha, group="Show Routes", color=website_route_palette) %>%
   addCircleMarkers(data = website_stops_sf, popup = website_stops_sf$STP_DESCRI, group = "Show Stops", color = "black", radius = 0.05) %>%
   addLayersControl(
     overlayGroups = ("Show Stops"),
     options = layersControlOptions(collapsed = FALSE)
   )

the_map
```


