---
title: "Clean-Data.Rmd"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
library(gtools)
library(tmaptools)
library(lubridate)
library(gsubfn)
WORKING_DIR <- "/Users/harrisonli/Documents/iCloud_Documents/Stanford/DAMS/AC_Transit/CusRel-Dashboard"
```


```{r}
raw_data <- read_csv("CusRel-Data.csv")
raw_stops <- read_csv("AC_transit_all_stops.csv")
```

```{r}
# Change StopID in stops data to character, remove irrelevant columns
stops <- raw_stops %>%
  dplyr::select(StopId, Latitude, Longitude) %>%
  mutate(StopId = as.character(StopId))
```


```{r}
# Add City, if known, else add ", CA USA" to location
raw_data <- raw_data %>%
  mutate(Location = if_else(substr(Location, nchar(Location)-3, nchar(Location)) == " USA", 
                            substr(Location, 1, nchar(Location)-4), Location), # get rid of USA in addresses
         Location = if_else(str_detect(Location, "#"), "NA", Location),
         GeocodeExtras = if_else(IncidentCity=="NULL", "CA USA", IncidentCity)) %>% 
  unite(col=GeocodeLocation, Location, GeocodeExtras, sep=" ", remove=FALSE)

```


```{r}
# Try geocoding locations, working by chunk
# raw_geocodes <- list()
# chunk_size <- 100
# for (i in 109:ceiling(nrow(raw_data)/chunk_size)){
  # cat(chunk_size*(i-1)+1, "\n")
  # raw_geocodes[[i]] <- geocode_OSM(raw_data$GeocodeLocation[(chunk_size*(i-1)+1):(min(chunk_size*i, nrow(raw_data)))], keep.unfound=TRUE)
# }
# raw_geocodes <- do.call("rbind", raw_geocodes)
```

```{r}
# Save raw geocodes so we don't have to run again from scratch
# write_csv(x=raw_geocodes, file=paste(WORKING_DIR, "/Raw-Geocodes.csv", sep=""))
```

```{r}
raw_geocodes <- read.csv(paste(WORKING_DIR, "/Raw-Geocodes.csv", sep=""))
```

```{r}
# Filter out geocodes not in within bbox of stops
xmin <- min(stops$Longitude)
xmax <- max(stops$Longitude)
ymin <- min(stops$Latitude)
ymax <- max(stops$Latitude)
geocodes <- raw_geocodes %>%
  mutate(Longitude=ifelse((lon >= xmin & lon <= xmax & lat >= ymin & lat <= ymax),
                            lon, NA),
         Latitude=ifelse((lon >= xmin & lon <= xmax & lat >= ymin & lat <= ymax),
                            lat, NA))
```

```{r}
# Get lat/lon from stop ID's, if we can
stop_lon_lat <- raw_data %>% 
  mutate(StopId=ifelse(grepl(pattern=".*\\(\\d\\d\\d\\d\\d\\)$", x=Location), 
                       substr(Location, nchar(Location)-5, nchar(Location)-1), 
                       NA)) %>%
  left_join(stops, by="StopId") # add lat lon to table based on stops data
```

```{r}
# Generate lat/lon columns, prioritizing those from stop ID's, ignoring those for which
cleaned_data <- raw_data %>%
  mutate(Longitude=if_else(is.na(stop_lon_lat$Longitude), geocodes$Longitude, stop_lon_lat$Longitude),
         Latitude=if_else(is.na(stop_lon_lat$Latitude), geocodes$Latitude, stop_lon_lat$Latitude)) %>%
  tidyr::separate(Reasons, into = c("Reason1", "Reason2"), sep = ";", fill = "right", extra = "drop") %>%
  dplyr::filter(!is.na(Longitude) & !is.na(Latitude))
```


```{r}
# Put in Pacific Time Zone, add day of week
cleaned_data <- cleaned_data %>%
  mutate(ReceivedDateTime=as.POSIXlt(as.character(ReceivedDateTime), tz="PST8PDT"),
         ResolvedDateTime=as.POSIXlt(as.character(ResolvedDateTime), tz="PST8PDT"),
         IncidentDateTime=as.POSIXlt(as.character(IncidentDateTime), tz="PST8PDT"),
         updatedOn=as.POSIXlt(as.character(updatedOn), tz="PST8PDT"))
```


```{r}
# Add Resolve Time, Incident + Received Date; Clean Incident City; Create Label for Popup
cleaned_data <- cleaned_data %>% 
  mutate(ResolveTime = round(as.numeric(difftime(as.POSIXct(ResolvedDateTime), as.POSIXct(ReceivedDateTime), units = "days"))), 
         ReceivedDate = as.Date(ReceivedDateTime, "%m/%d/%y", tz="PST8PDT"),
         ReceivedDateDay=wday(ReceivedDate, label=TRUE, abbr=FALSE),
         IncidentDate = as.Date(IncidentDateTime, "%m/%d/%y", tz="PST8PDT"), 
         IncidentCity = gsubfn(".*", list("BERKELEY" = "Berkeley", "El Ceritto" = "El Cerrito", "Freemont" = "Fremont", "hayward" = "Hayward", "Menlo park" = "Menlo Park", "oakland" = "Oakland", "Pittsburgh Bay point" = "Pittsburgh Bay Point", "San francisco" = "San Francisco"), IncidentCity),
         Route = toupper(Route),
         Label = str_c("<b>Priority:</b> ", Priority, "<br/>",
                       "<b>Respond Via:</b> ", RespondVia, " &nbsp;&nbsp ", "<b>Contact Source:</b> ", ContactSource, "<br/>",
                       
                       "<b>Received Date:</b> ", ReceivedDate, "<br/>",
                       "<b>Incident Date:</b> ", IncidentDate, "<br/>",
                       "<b>Day of the Week:</b> ", ReceivedDateDay, "<br/>",
                       "<b>Incident City:</b> ", IncidentCity, "<br/>",
                       "<b>Location:</b> ", Location, "<br/>", 
                       "<b>Destination:</b> ", Destination , "<br/>",
                       "<b>Route:</b> ", Route, " &nbsp;&nbsp ", "<b>Vehicle #:</b> ", VehNo, "<br/>", 
                       "<b>Resolve Time:</b> ", ResolveTime, " day(s)<br/>", 
                       "<b>Reason(s):</b> ", Reason1, if_else(is.na(Reason2), "", str_c("; ", Reason2)), "<br/>",
                       "<b>Title VI:</b> ", TitleVI, " &nbsp;&nbsp ", "<b>ADA Complaint:</b> ", ADAComplaint, "<br/>", 
                       "<b>Department:</b> ", ForAction, "<br/>",
                       "<b>Ticket Number:</b> ", FileNum)) # Add a Label for Popup 

```

```{r}
# Change N/A and NULL into Unknown; add reason columns, day of week
clean_data <- cleaned_data %>%
  mutate(IncidentCity = ifelse((IncidentCity %in% c("NULL", "N/A")), "Unknown", IncidentCity),
         Route = ifelse((Route %in% c("NULL", "N/A") | is.na(Route)), "Unknown", Route),
         ForAction = ifelse(is.na(ForAction), "Unknown", ForAction),
         Reason1=if_else(grepl(pattern="\\d\\d\\.\\s.*$", x=Reason1), str_sub(Reason1, 5), Reason1),
         Reason2=if_else(grepl(pattern="\\d\\d\\.\\s.*$", x=Reason2), str_sub(Reason2, 5), Reason2),
         ForAction=if_else(grepl(pattern=".*\\.\\s", x=ForAction), sapply(str_split(ForAction, " "), function(x) str_c(x[-1], collapse=" ")), ForAction),
         ReceivedDateDay=wday(ReceivedDate, label=TRUE, abbr=FALSE))
```

```{r}
# Write out
write_csv(clean_data, paste(WORKING_DIR, "/Clean-CusRel-data.csv", sep=""))
```



